logging:
  level:
    gov:
      nist:
        javax:
          sip: WARN
    com:
      sipgate:
        sipvalidator: DEBUG
    root: INFO
spring:
  thymeleaf:
    cache: 'false'
server:
  port: '8080'
